### PR TITLE
Re-register HTML dependencies on cache read

### LINKED ISSUE #396: Cached render doesn't register widget's HTML dependencies as web dependencies
To reproduce, first run this example, then restart your R session and re-run the app.

```r
library(shiny)
library(plotly)
shinyOptions(cache = cachem::cache_disk("./myapp-cache"))
ui <- fluidPage(
  plotlyOutput("p")
)
server <- function(input, output, session) {
  output$p <- renderPlotly(plot_ly()) %>%
    bindCache(1)
}
shinyApp(ui, server)
```

On the second time (i.e., the cache hit), the plot won't appear because the HTML dependencies aren't being registered as resource paths. That is, this code isn't being run on a cache hit

https://github.com/ramnathv/htmlwidgets/blob/48860020e9369b3e350f65aba37814c6913cf722/R/htmlwidgets.R#L535-L539

### PR DESCRIPTION
**Pull request by wch**
Fixes #396. This depends on https://github.com/rstudio/shiny/pull/3173.

### CODE REVIEW

File: R/htmlwidgets.R [hunk 1]
```diff
@@ -533,24 +533,39 @@ shinyRenderWidget <- function(expr, outputFunction, env, quoted, cacheHint = "au
...
+        # dependencies again.
+        deps <- attr(value, "deps")
+        lapply(
+          htmltools::resolveDependencies(deps),
+          shiny::createWebDependency
+        )
+        value
+      }
+
+
```
Comment (cpsievert) [inline R/htmlwidgets.R:568]:
```suggestion
```

Comment (cpsievert) [inline R/htmlwidgets.R:568]:
```suggestion
      }
```

File: R/htmlwidgets.R [hunk 2]
```diff
@@ -533,24 +533,39 @@ shinyRenderWidget <- function(expr, outputFunction, env, quoted, cacheHint = "au
...
     )
```
Comment (cpsievert) [inline R/htmlwidgets.R:569]:
```suggestion
        value
      }
    )
```

**Review by cpsievert — APPROVED** [review]
